// test/workday-oracle.test.mjs — run with:  node --test
//
// WHY THIS EXISTS. The golden fixture's _cachedDue fields are the Excel workbook's
// outputs under the RETIRED Sat/Sun weekend, so when the weekend flipped to Fri/Sat
// (stakeholder decision 2026-08-05) those oracle comparisons were scoped out — leaving
// the weekend rule pinned only by tests that call workday() itself. A single edit to
// the dow check would then move the engine and its "auditors" together, silently.
//
// This table is the replacement oracle: 21 (received-weekday × TAT) pairs DERIVED BY
// HAND on a calendar — never generated by workday() — covering every weekday of the
// week of Sunday 2026-07-05. Business days are Sun–Thu; Friday and Saturday are the
// weekend; counting starts the day AFTER receipt.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { workday, toEpochDay, parseDateTime } from '../src/engine/workday.js';

const iso = (ms) => new Date(ms).toISOString().slice(0, 10);
const due = (received, tat) => iso(workday(toEpochDay(parseDateTime(received)), tat));

// [received (weekday), tat, expected due (weekday)] — hand-derived, frozen.
const ORACLE = [
  ['2026-07-05', 1, '2026-07-06'], // Sun +1 → Mon
  ['2026-07-05', 2, '2026-07-07'], // Sun +2 → Tue
  ['2026-07-05', 5, '2026-07-12'], // Sun +5 → next Sun (skips Fri 10 / Sat 11)
  ['2026-07-06', 1, '2026-07-07'], // Mon +1 → Tue
  ['2026-07-06', 2, '2026-07-08'], // Mon +2 → Wed
  ['2026-07-06', 5, '2026-07-13'], // Mon +5 → next Mon
  ['2026-07-07', 1, '2026-07-08'], // Tue +1 → Wed
  ['2026-07-07', 2, '2026-07-09'], // Tue +2 → Thu
  ['2026-07-07', 5, '2026-07-14'], // Tue +5 → next Tue
  ['2026-07-08', 1, '2026-07-09'], // Wed +1 → Thu
  ['2026-07-08', 2, '2026-07-12'], // Wed +2 → SUN (Thu 09 is day 1; Fri/Sat skipped)
  ['2026-07-08', 5, '2026-07-15'], // Wed +5 → next Wed
  ['2026-07-09', 1, '2026-07-12'], // Thu +1 → Sun (weekend skipped)
  ['2026-07-09', 2, '2026-07-13'], // Thu +2 → Mon
  ['2026-07-09', 5, '2026-07-16'], // Thu +5 → next Thu
  ['2026-07-10', 1, '2026-07-12'], // Fri (weekend) +1 → Sun
  ['2026-07-10', 2, '2026-07-13'], // Fri +2 → Mon
  ['2026-07-10', 5, '2026-07-16'], // Fri +5 → Thu
  ['2026-07-11', 1, '2026-07-12'], // Sat (weekend) +1 → Sun
  ['2026-07-11', 2, '2026-07-13'], // Sat +2 → Mon
  ['2026-07-11', 5, '2026-07-16'], // Sat +5 → Thu
];

test('workday() matches the hand-derived Fri/Sat-weekend oracle (21 pairs, all weekdays)', () => {
  for (const [received, tat, expected] of ORACLE) {
    assert.equal(due(received, tat), expected, `received ${received} + ${tat} business days`);
  }
});

test('no due date ever lands on Friday or Saturday', () => {
  for (let d = 0; d < 14; d++) {
    const start = new Date(Date.UTC(2026, 6, 1 + d)).toISOString().slice(0, 10);
    for (let tat = 1; tat <= 10; tat++) {
      const dow = new Date(workday(toEpochDay(parseDateTime(start)), tat)).getUTCDay();
      assert.ok(dow !== 5 && dow !== 6, `due for ${start}+${tat} landed on weekday ${dow}`);
    }
  }
});
